version: '3.3'

services:

  backend:
    container_name: qr_code_generator_backend
    hostname: qr_code_generator_backend
    build: ./backend
    image: ghcr.io/trisnol/qr-code-generator-backend

    ports:
      - 3000:3000
    restart: unless-stopped

  frontend:
    container_name: qr_code_generator_frontend
    hostname: qr_code_generator_frontend
    build: ./frontend
    image: ghcr.io/trisnol/qr-code-generator-frontend

    ports:
      - 80:80
    restart: unless-stopped
    environment:
      - API_URL=http://localhost:3000
    depends_on:
      - backend
